import Foundation

// MARK: - Foundation Models Recipe Generator (iOS 26+)

// The Foundation Models framework is only available on iOS 26+ / macOS 26+.
// We use @available checks and a protocol-based fallback so the core app
// works on all devices, with AI recipe generation as an optional enhancement.

/// A recipe generated by Foundation Models or returned as a fallback.
struct GeneratedRecipeResult: Sendable {
  let title: String
  let timeMinutes: Int
  let servings: Int
  let instructions: String
  let estimatedCaloriesPerServing: Int
  let isAIGenerated: Bool
}

/// Protocol for recipe generation — allows swapping AI vs fallback.
protocol RecipeGenerating: Sendable {
  func generate(
    from ingredientNames: [String],
    dietaryRestrictions: [String]
  ) async throws -> GeneratedRecipeResult?
}

// MARK: - AI Generator (iOS 26+)
// Uncomment when building with Xcode 26 / iOS 26 SDK:
//
// import FoundationModels
//
// @available(iOS 26, macOS 26, *)
// @Generable
// struct AIGeneratedRecipe {
//     @Guide(description: "A creative, appetizing recipe title")
//     let title: String
//
//     @Guide(description: "Cooking time in minutes")
//     let timeMinutes: Int
//
//     @Guide(description: "Number of servings this recipe makes")
//     let servings: Int
//
//     @Guide(description: "Step-by-step cooking instructions, numbered")
//     let instructions: String
//
//     @Guide(description: "Estimated calories per serving")
//     let estimatedCaloriesPerServing: Int
// }
//
// @available(iOS 26, macOS 26, *)
// final class AIRecipeGenerator: RecipeGenerating {
//     private var session: LanguageModelSession
//
//     init() {
//         self.session = LanguageModelSession(instructions: """
//             You are a practical home cooking assistant. Create simple, realistic recipes
//             that a university student could make with basic kitchen equipment.
//             Focus on taste, nutrition, and simplicity. Assume access to basic pantry
//             staples (salt, pepper, oil, butter) without listing them as ingredients.
//             """)
//     }
//
//     func generate(
//         from ingredientNames: [String],
//         dietaryRestrictions: [String]
//     ) async throws -> GeneratedRecipeResult? {
//         guard SystemLanguageModel.default.isAvailable else { return nil }
//
//         var prompt = "Create a recipe using these ingredients: \(ingredientNames.joined(separator: ", "))."
//         if !dietaryRestrictions.isEmpty {
//             prompt += " Dietary requirements: \(dietaryRestrictions.joined(separator: ", "))."
//         }
//
//         let response = try await session.respond(to: prompt, generating: AIGeneratedRecipe.self)
//         let r = response.content
//         return GeneratedRecipeResult(
//             title: r.title,
//             timeMinutes: r.timeMinutes,
//             servings: r.servings,
//             instructions: r.instructions,
//             estimatedCaloriesPerServing: r.estimatedCaloriesPerServing,
//             isAIGenerated: true
//         )
//     }
// }

// MARK: - Fallback Generator (All Devices)

/// Returns the best-matching bundled recipe when Foundation Models is unavailable.
final class FallbackRecipeGenerator: RecipeGenerating {
  private let recipeRepository: RecipeRepository

  init(recipeRepository: RecipeRepository) {
    self.recipeRepository = recipeRepository
  }

  func generate(
    from ingredientNames: [String],
    dietaryRestrictions: [String]
  ) async throws -> GeneratedRecipeResult? {
    // Map ingredient names back to IDs
    let ids: Set<Int64> = Set(
      ingredientNames.compactMap { name in
        IngredientLexicon.resolve(name)
      })

    guard !ids.isEmpty else { return nil }

    let profile = HealthProfile.default
    guard let best = try recipeRepository.quickSuggestion(with: ids, profile: profile) else {
      return nil
    }

    return GeneratedRecipeResult(
      title: best.recipe.title,
      timeMinutes: best.recipe.timeMinutes,
      servings: best.recipe.servings,
      instructions: best.recipe.instructions,
      estimatedCaloriesPerServing: Int(best.macros.caloriesPerServing),
      isAIGenerated: false
    )
  }
}

// MARK: - Factory

enum RecipeGeneratorFactory {
  /// Returns the best available generator for the current device.
  static func create(recipeRepository: RecipeRepository) -> RecipeGenerating {
    // When building with iOS 26 SDK, uncomment:
    // if #available(iOS 26, macOS 26, *) {
    //     if SystemLanguageModel.default.isAvailable {
    //         return AIRecipeGenerator()
    //     }
    // }
    return FallbackRecipeGenerator(recipeRepository: recipeRepository)
  }
}
