import Foundation

#if canImport(FoundationModels)
  import FoundationModels
#endif

// MARK: - Foundation Models Recipe Generator (iOS 26+)

/// A recipe generated by Foundation Models or returned as a fallback.
struct GeneratedRecipeResult: Sendable {
  let title: String
  let timeMinutes: Int
  let servings: Int
  let instructions: String
  let estimatedCaloriesPerServing: Int
  let isAIGenerated: Bool
}

enum AIEnhancementAvailability: Sendable {
  case available
  case unavailable(String)

  var noticeText: String? {
    switch self {
    case .available:
      return nil
    case .unavailable(let message):
      return message
    }
  }
}

/// Protocol for recipe generation — allows swapping AI vs fallback.
protocol RecipeGenerating: Sendable {
  var enhancementAvailability: AIEnhancementAvailability { get }

  func generate(
    from ingredientNames: [String],
    dietaryRestrictions: [String]
  ) async throws -> GeneratedRecipeResult?
}

// MARK: - AI Generator (iOS 26+)

#if canImport(FoundationModels)
  @available(iOS 26.0, macOS 26.0, *)
  @Generable
  struct AIGeneratedRecipe {
    @Guide(description: "A practical and appetizing recipe title")
    let title: String

    @Guide(description: "Cooking time in minutes")
    let timeMinutes: Int

    @Guide(description: "Number of servings this recipe makes")
    let servings: Int

    @Guide(description: "Step-by-step instructions as concise numbered steps")
    let instructions: String

    @Guide(description: "Estimated calories per serving")
    let estimatedCaloriesPerServing: Int
  }

  @available(iOS 26.0, macOS 26.0, *)
  final class AIRecipeGenerator: RecipeGenerating, @unchecked Sendable {
    private let model = SystemLanguageModel.default
    private let session = LanguageModelSession(
      instructions: """
        You are a practical home-cooking assistant.
        Produce realistic, concise recipes that use the provided ingredients first.
        Keep instructions clear and executable with basic kitchen tools.
        """
    )

    var enhancementAvailability: AIEnhancementAvailability { .available }

    func generate(
      from ingredientNames: [String],
      dietaryRestrictions: [String]
    ) async throws -> GeneratedRecipeResult? {
      guard case .available = model.availability else { return nil }

      let ingredientLine = ingredientNames.joined(separator: ", ")
      var prompt = "Create one recipe using these ingredients: \(ingredientLine)."
      if !dietaryRestrictions.isEmpty {
        prompt += " Respect dietary restrictions: \(dietaryRestrictions.joined(separator: ", "))."
      }

      let response = try await session.respond(
        to: prompt,
        generating: AIGeneratedRecipe.self
      )

      let result = response.content
      return GeneratedRecipeResult(
        title: result.title,
        timeMinutes: max(5, result.timeMinutes),
        servings: max(1, result.servings),
        instructions: result.instructions,
        estimatedCaloriesPerServing: max(50, result.estimatedCaloriesPerServing),
        isAIGenerated: true
      )
    }
  }
#endif

// MARK: - Fallback Generator (All Devices)

/// Returns the best-matching bundled recipe when Foundation Models is unavailable.
final class FallbackRecipeGenerator: RecipeGenerating, @unchecked Sendable {
  private let recipeRepository: RecipeRepository
  private let ingredientResolver: IngredientCatalogResolving

  init(
    recipeRepository: RecipeRepository,
    ingredientResolver: IngredientCatalogResolving
  ) {
    self.recipeRepository = recipeRepository
    self.ingredientResolver = ingredientResolver
  }

  var enhancementAvailability: AIEnhancementAvailability {
    .unavailable("AI enhancement unavailable, using local fallback.")
  }

  func generate(
    from ingredientNames: [String],
    dietaryRestrictions: [String]
  ) async throws -> GeneratedRecipeResult? {
    let ids: Set<Int64> = Set(
      ingredientNames.compactMap { name in
        ingredientResolver.resolve(name) ?? IngredientLexicon.resolve(name)
      }
    )

    guard !ids.isEmpty else { return nil }

    var profile = HealthProfile.default
    if let data = try? JSONEncoder().encode(dietaryRestrictions),
      let json = String(data: data, encoding: .utf8)
    {
      profile.dietaryRestrictions = json
    }

    guard let best = try recipeRepository.quickSuggestion(with: ids, profile: profile) else {
      return nil
    }

    return GeneratedRecipeResult(
      title: best.recipe.title,
      timeMinutes: best.recipe.timeMinutes,
      servings: best.recipe.servings,
      instructions: best.recipe.instructions,
      estimatedCaloriesPerServing: Int(best.macros.caloriesPerServing),
      isAIGenerated: false
    )
  }
}

// MARK: - Factory

enum RecipeGeneratorFactory {
  /// Returns the best available generator for the current device.
  static func create(
    recipeRepository: RecipeRepository,
    ingredientResolver: IngredientCatalogResolving
  ) -> RecipeGenerating {
    #if canImport(FoundationModels)
      if #available(iOS 26.0, macOS 26.0, *) {
        let model = SystemLanguageModel.default
        if case .available = model.availability {
          return AIRecipeGenerator()
        }
      }
    #endif

    return FallbackRecipeGenerator(
      recipeRepository: recipeRepository,
      ingredientResolver: ingredientResolver
    )
  }
}
