import Foundation

// GENERATED by scripts/data/evaluate_mass_estimates.py from
// apps/ios/Platform/Persistence/Services/InventoryIntakeService.swift
// at commit 5e3eae7276f5bf5d7c16e749d7b0331d1da5ec2a. DO NOT EDIT by hand — re-run the script to regenerate.
//
// Verbatim slice of the production gram estimator. Mechanical transforms
// applied to each block: `private static` -> `public static` (accessibility
// widening only, so the replay executable can call the members), and
// `Ingredient?` -> the minimal `ReplayIngredient?` stand-in so the slice
// compiles off iOS. Everything else (logic, thresholds, keyword tables) is
// byte-identical.

public struct ReplayIngredient {
  public var typicalUnit: String?
  public init(typicalUnit: String?) {
    self.typicalUnit = typicalUnit
  }
}

public enum EstimatorReplay {
  public static let pantryLocationKeywords = [
    "rice", "pasta", "oil", "sauce", "bread", "tortilla", "oat", "bean", "chickpea", "corn",
    "garlic", "onion", "honey", "peanut butter", "canned", "ginger",
  ]

  public static let fridgeLocationKeywords = [
    "milk", "yogurt", "cheese", "butter", "egg", "spinach", "lettuce", "pepper", "tomato",
    "carrot", "broccoli", "cucumber", "zucchini", "celery", "avocado", "apple", "banana",
    "lemon", "lime", "salmon", "chicken", "beef", "tofu", "mushroom",
  ]

  public static let liquidMassKeywords = ["milk", "yogurt"]

  public static let oilAndCondimentKeywords = [
    "oil", "sauce", "honey", "mustard", "peanut butter", "sesame",
  ]

  public static let leafyProduceKeywords = [
    "spinach", "lettuce", "cilantro", "herb", "green onion",
  ]

  public static let aromaticKeywords = ["garlic", "ginger", "chive"]

  public static let proteinKeywords = ["chicken", "beef", "salmon", "tofu", "tuna"]

  public static let dryGoodsKeywords = [
    "rice", "pasta", "bean", "chickpea", "oat", "corn", "pea",
  ]

  public static let breadKeywords = ["bread", "tortilla"]

  public static let produceKeywords = [
    "onion", "tomato", "pepper", "potato", "carrot", "mushroom", "broccoli", "cucumber",
    "avocado", "apple", "banana", "lemon", "lime", "zucchini", "celery",
  ]

  public static func estimatedGrams(for ingredient: ReplayIngredient?) -> Double {
    guard let typicalUnit = ingredient?.typicalUnit?.lowercased() else { return 120 }

    if let grams = extractNumber(from: typicalUnit, unitTokens: ["g", "gram", "grams"]) {
      return max(20, grams)
    }

    if let ounces = extractNumber(from: typicalUnit, unitTokens: ["oz", "ounce", "ounces"]) {
      return max(20, ounces * 28.3495)
    }

    if typicalUnit.contains("cup") { return 240 }
    if typicalUnit.contains("tbsp") || typicalUnit.contains("tablespoon") { return 15 }
    if typicalUnit.contains("tsp") || typicalUnit.contains("teaspoon") { return 5 }
    if typicalUnit.contains("slice") { return 35 }
    if typicalUnit.contains("piece") || typicalUnit.contains("whole") { return 90 }

    return 120
  }

  public static func estimatedGrams(forName ingredientName: String?) -> Double {
    guard let normalizedName = normalizeIngredientName(ingredientName) else { return 120 }

    if normalizedName.contains("egg") { return 50 }
    if liquidMassKeywords.contains(where: normalizedName.contains) { return 240 }
    if oilAndCondimentKeywords.contains(where: normalizedName.contains) { return 30 }
    if leafyProduceKeywords.contains(where: normalizedName.contains) { return 40 }
    if aromaticKeywords.contains(where: normalizedName.contains) { return 20 }
    if proteinKeywords.contains(where: normalizedName.contains) { return 150 }
    if dryGoodsKeywords.contains(where: normalizedName.contains) { return 180 }
    if breadKeywords.contains(where: normalizedName.contains) { return 60 }
    if produceKeywords.contains(where: normalizedName.contains) { return 120 }

    return 120
  }

  public static func normalizeIngredientName(_ ingredientName: String?) -> String? {
    guard let ingredientName else { return nil }

    let normalizedName =
      ingredientName
      .trimmingCharacters(in: .whitespacesAndNewlines)
      .lowercased()
    guard !normalizedName.isEmpty else { return nil }

    return normalizedName
  }

  public static func extractNumber(from text: String, unitTokens: [String]) -> Double? {
    let pattern = "([0-9]+(?:\\.[0-9]+)?)\\s*(\\b(?:" + unitTokens.joined(separator: "|") + ")\\b)"
    guard let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) else {
      return nil
    }

    let fullRange = NSRange(text.startIndex..<text.endIndex, in: text)
    guard let match = regex.firstMatch(in: text, options: [], range: fullRange),
      match.numberOfRanges >= 2,
      let numberRange = Range(match.range(at: 1), in: text)
    else {
      return nil
    }

    return Double(text[numberRange])
  }
}
