import XCTest
@testable import SearchCheck

/// Retrieval-quality evaluation over a frozen corpus and a frozen query set.
///
/// The corpus (Tests/SearchCheckTests/Fixtures/corpus.json) is generated by
/// Scripts/gen_corpus.py and committed; expectations come from a
/// construction-based oracle that re-implements the matching contract
/// independently of the engine's code path, so a regression in
/// tokenization, matching, or ranking shows up as a metric drop rather than
/// a silent pass.
///
/// Thresholds: every frozen query must reach full recall within its expected
/// set size (K) and precision at K >= 0.95. The full report (per-query
/// metrics plus top-3 hits for annotation) is written to EVAL_REPORT_PATH
/// when that environment variable is set.
final class SearchEvalTests: XCTestCase {
  private struct QueryResult {
    let query: String
    let expected: [String]
    let topIDs: [String]
    let recallAtK: Double
    let precisionAtK: Double
    let mrr: Double
  }

  func testFrozenCorpusReachesFullRecallOnAllQueries() throws {
    let corpus = try EvalCorpus.load()
    let store = try SearchIndexStore()
    try store.rebuild(with: corpus.documents, sourceEpoch: "eval-corpus")

    var results: [QueryResult] = []
    for frozen in corpus.queries {
      let tokens = SearchText.tokens(in: frozen.q)
      guard let expression = SearchEngine.matchExpression(for: tokens) else {
        XCTFail("query produced no match expression: \(frozen.q)")
        continue
      }
      let rawHits = try store.fetchHits(match: expression, kinds: nil, limit: 100)
      let ranked = SearchEngine.rank(rawHits, query: frozen.q)
      let rankedIDs = ranked.map { $0.canonicalID.description }

      let k = max(frozen.expected.count, 1)
      let topK = Array(rankedIDs.prefix(k))
      let expected = Set(frozen.expected)
      let hitsInTopK = topK.filter { expected.contains($0) }
      let recall = Double(hitsInTopK.count) / Double(k)
      let precision = Double(hitsInTopK.count) / Double(max(topK.count, 1))
      let reciprocalRank: Double = {
        for (index, id) in rankedIDs.enumerated() where expected.contains(id) {
          return 1.0 / Double(index + 1)
        }
        return 0
      }()

      results.append(
        QueryResult(
          query: frozen.q,
          expected: frozen.expected,
          topIDs: Array(rankedIDs.prefix(3)),
          recallAtK: recall,
          precisionAtK: precision,
          mrr: reciprocalRank))

      let missing = frozen.expected.filter { !topK.contains($0) }
      XCTAssertTrue(
        missing.isEmpty,
        "query \"\(frozen.q)\" missed expected docs in top \(k): \(missing); top hits: \(topK)")
      XCTAssertGreaterThanOrEqual(
        precision, 0.95,
        "query \"\(frozen.q)\" precision@\(k) = \(precision)")
    }

    let meanRecall = results.map { $0.recallAtK }.reduce(0, +) / Double(results.count)
    let meanPrecision = results.map { $0.precisionAtK }.reduce(0, +) / Double(results.count)
    let meanMRR = results.map { $0.mrr }.reduce(0, +) / Double(results.count)
    XCTAssertEqual(results.count, corpus.queries.count)
    XCTAssertEqual(meanRecall, 1.0, accuracy: 1e-9)
    XCTAssertEqual(meanMRR, 1.0, accuracy: 1e-9)

    if let reportPath = ProcessInfo.processInfo.environment["EVAL_REPORT_PATH"] {
      try writeReport(
        corpus: corpus,
        results: results,
        meanRecall: meanRecall,
        meanPrecision: meanPrecision,
        meanMRR: meanMRR,
        to: reportPath)
    }
  }

  private func writeReport(
    corpus: EvalCorpus,
    results: [QueryResult],
    meanRecall: Double,
    meanPrecision: Double,
    meanMRR: Double,
    to path: String
  ) throws {
    let report: [String: Any] = [
      "corpusVersion": corpus.version,
      "documentCount": corpus.docs.count,
      "queryCount": results.count,
      "metrics": [
        "mean_recall_at_k": meanRecall,
        "mean_precision_at_k": meanPrecision,
        "mean_mrr": meanMRR,
      ],
      "queries": results.map { result in
        [
          "query": result.query,
          "expected": result.expected,
          "top3": result.topIDs,
          "recall_at_k": result.recallAtK,
          "precision_at_k": result.precisionAtK,
          "mrr": result.mrr,
        ]
      }
    ]

    let data = try JSONSerialization.data(
      withJSONObject: report, options: [.prettyPrinted, .sortedKeys])
    try data.write(to: URL(fileURLWithPath: path))
  }
}
