import CryptoKit
import XCTest

@testable import FridgeLuck

/// Production replay for the substitution evidence harness.
///
/// Re-parses the live `SubstitutionService.swift` source (located relative to
/// this file so it runs on any checkout) with the same extraction the Python
/// evidence harness uses, then verifies the frozen evidence fixture matches.
/// The fixture is generated by
/// `apps/ios/Tools/substitution-eval/tools/render_swift_fixture.py` from
/// `evidence/pairs.snapshot.json`; if either side drifts, these tests fail.
final class SubstitutionEvidenceReplayTests: XCTestCase {
  private struct ParsedPair: Equatable {
    let originalId: Int
    let substituteId: Int
    let ratio: Double
    let reasons: [String]
  }

  // MARK: - Production parsing (port of tools/extract_production_map.py)

  private static let knownReasons: Set<String> = [
    "vegan", "dairyFree", "glutenFree", "vegetarian", "lighter", "lowCarb", "similar",
  ]

  /// The `buildMap()` region is the single source of truth.
  private static func buildMapRegion(in source: String) throws -> String {
    guard let start = source.range(of: "private static func buildMap()") else {
      throw ReplayError.regionMarkerNotFound("private static func buildMap()")
    }
    let tail = String(source[start.upperBound...])
    guard let end = tail.range(of: "return map") else {
      throw ReplayError.regionMarkerNotFound("return map")
    }
    return String(tail[..<end.lowerBound])
  }

  private static func parsePairs(from region: String) throws -> [ParsedPair] {
    // add(\s*(\d+)\s*,\s*(\d+)\s*,\s*reasons:\s*\[([^\]]*)\]\s*,\s*ratio:\s*([0-9.]+)
    let pattern =
      #"add\(\s*(\d+)\s*,\s*(\d+)\s*,\s*reasons:\s*\[([^\]]*)\]\s*,\s*ratio:\s*([0-9.]+)"#
    let regex = try NSRegularExpression(pattern: pattern)
    let range = NSRange(region.startIndex..<region.endIndex, in: region)

    return try regex.matches(in: region, range: range).map { match in
      func group(_ index: Int) -> String {
        let r = match.range(at: index)
        guard let gr = Range(r, in: region) else { return "" }
        return String(region[gr])
      }

      let originalId = Int(group(1))!
      let substituteId = Int(group(2))!
      let ratio = Double(group(4))!
      let reasons = group(3)
        .split(separator: ",")
        .map { $0.trimmingCharacters(in: .whitespaces).trimmingCharacters(in: CharacterSet(charactersIn: ".")) }
        .filter { !$0.isEmpty }
      for reason in reasons where !knownReasons.contains(reason) {
        throw ReplayError.unknownReasonCase(reason)
      }
      return ParsedPair(
        originalId: originalId, substituteId: substituteId, ratio: ratio, reasons: reasons)
    }
  }

  private enum ReplayError: Error {
    case regionMarkerNotFound(String)
    case unknownReasonCase(String)
  }

  // MARK: - Loading

  private static func repositoryRoot(for file: StaticString = #filePath) -> URL {
    // This test lives at apps/ios/Tests/; walk up: file -> Tests -> ios -> apps -> root.
    var url = URL(fileURLWithPath: "\(file)")
    for _ in 0..<4 { url.deleteLastPathComponent() }
    return url
  }

  private static func parseProduction() throws -> (pairs: [ParsedPair], regionSHA256: String) {
    let serviceURL = repositoryRoot()
      .appendingPathComponent("apps/ios/Platform/Persistence/Services/SubstitutionService.swift")
    let source = try String(contentsOf: serviceURL, encoding: .utf8)
    let region = try buildMapRegion(in: source)
    let digest = SHA256.hash(data: Data(region.utf8))
    let hex = digest.map { String(format: "%02x", $0) }.joined()
    return (try parsePairs(from: region), hex)
  }

  // MARK: - Tests

  func testProductionPairsMatchTheFrozenEvidenceFixture() throws {
    let (parsed, _) = try Self.parseProduction()
    let fixture = SubstitutionEvidenceSnapshot.pairs

    let parsedPairs = parsed.map {
      [$0.originalId, $0.substituteId, $0.ratio, $0.reasons] as [AnyHashable]
    }
    let fixturePairs = fixture.map {
      [$0.originalId, $0.substituteId, $0.ratio, $0.reasons] as [AnyHashable]
    }
    XCTAssertEqual(parsedPairs, fixturePairs, "SubstitutionService.swift drifted from the evidence snapshot")
  }

  func testSourceRegionHashMatchesTheFixture() throws {
    let (_, regionSHA256) = try Self.parseProduction()
    XCTAssertEqual(regionSHA256, SubstitutionEvidenceSnapshot.sourceRegionSHA256)
  }

  func testEveryPairHasPositiveFiniteRatioAndDistinctIngredients() {
    for pair in SubstitutionEvidenceSnapshot.pairs {
      XCTAssert(pair.ratio > 0 && pair.ratio.isFinite, "bad ratio in \(pair)")
      XCTAssertNotEqual(pair.originalId, pair.substituteId, "self-swap in \(pair)")
      XCTAssertFalse(pair.reasons.isEmpty, "no reasons in \(pair)")
    }
  }

  func testFixturePairCountMatchesTheSnapshotField() {
    // 27 production pairs as frozen in the evidence snapshot.
    XCTAssertEqual(SubstitutionEvidenceSnapshot.pairs.count, 27)
  }
}
