import CryptoKit
import GRDB
import XCTest

@testable import FridgeLuck

/// SwiftReplay — production replay for the substitution evidence harness.
///
/// Runs the real `SubstitutionService` (its map built exactly as in
/// production) over every frozen evidence pair and every generated (pair,
/// bundled recipe) context case, and asserts the production suggestions match
/// the frozen evidence: same substitute, same ratio, same reasons. The source
/// region SHA-256 guards against silent edits to `SubstitutionService.swift`.
///
/// Fixtures are generated by
/// `apps/ios/Tools/substitution-eval/tools/render_swift_fixture.py` from
/// `evidence/pairs.snapshot.json` and `evidence/context_cases.csv`; the
/// Python validator rejects a stale fixture, so evidence drift fails in both
/// directions.
final class SubstitutionEvidenceReplayTests: XCTestCase {
  // MARK: - Production service

  /// In-memory queue: `buildMap()` never reads the database, it is only held
  /// for `ingredient(id:)` lookups, which these tests do not exercise.
  private static func makeService() throws -> SubstitutionService {
    try SubstitutionService(db: DatabaseQueue())
  }

  private static let reasonByKey: [String: SubstitutionReason] = [
    "vegan": .vegan,
    "dairyFree": .dairyFree,
    "glutenFree": .glutenFree,
    "vegetarian": .vegetarian,
    "lighter": .lighter,
    "lowCarb": .lowCarb,
    "similar": .similar,
  ]

  /// Legacy restriction IDs that map to a pair's reasons, mirroring
  /// `SubstitutionReason.reasons(forRestrictions:)`.
  private static func restrictions(forReasons reasons: [String]) -> Set<String> {
    var result: Set<String> = []
    for reason in reasons {
      switch reason {
      case "vegan":
        result.formUnion(["vegan"])
      case "vegetarian":
        result.formUnion(["vegetarian"])
      case "dairyFree":
        result.formUnion(["dairy_free"])
      case "glutenFree":
        result.formUnion(["gluten_free"])
      case "lowCarb":
        result.formUnion(["low_carb"])
      default:
        break  // lighter / similar carry no restriction ID
      }
    }
    return result
  }

  // MARK: - Source drift guard

  /// The hashed region: everything after the `private static func buildMap()`
  /// marker, up to `return map` — the same byte range the Python extractor
  /// hashes. Both sides must slice identically.
  private static func buildMapRegion(in source: String) throws -> String {
    let marker = "private static func buildMap()"
    guard let markerRange = source.range(of: marker) else {
      throw ReplayError.regionMarkerNotFound(marker)
    }
    let tail = source[markerRange.upperBound...]
    guard let end = tail.range(of: "return map") else {
      throw ReplayError.regionMarkerNotFound("return map")
    }
    return String(tail[..<end.lowerBound])
  }

  private static func sourceRegionSHA256() throws -> String {
    let root = repositoryRoot()
    let serviceURL = root
      .appendingPathComponent("apps/ios/Platform/Persistence/Services/SubstitutionService.swift")
    let source = try String(contentsOf: serviceURL, encoding: .utf8)
    let region = try buildMapRegion(in: source)
    let digest = SHA256.hash(data: Data(region.utf8))
    return digest.map { String(format: "%02x", $0) }.joined()
  }

  private static func repositoryRoot(for file: StaticString = #filePath) -> URL {
    // This test lives at apps/ios/Tests/; walk up: file -> Tests -> ios -> apps -> root.
    var url = URL(fileURLWithPath: "\(file)")
    for _ in 0..<4 { url.deleteLastPathComponent() }
    return url
  }

  private enum ReplayError: Error {
    case regionMarkerNotFound(String)
  }

  // MARK: - Production replay

  func testProductionSuggestionsReproduceEveryFrozenPair() throws {
    let service = try Self.makeService()
    for expected in SubstitutionEvidenceSnapshot.pairs {
      let suggestions = service.substitutions(for: Int64(expected.originalId))
      let match = suggestions.first { $0.substituteId == Int64(expected.substituteId) }
      guard let match else {
        XCTFail("production returned no suggestion for \(expected.originalId) -> \(expected.substituteId)")
        continue
      }
      XCTAssertEqual(match.ratio, expected.ratio, accuracy: 1e-12, "ratio drifted in \(expected)")
      let expectedReasons = Set(expected.reasons.compactMap { Self.reasonByKey[$0] })
      XCTAssertEqual(match.reasons, expectedReasons, "reasons drifted in \(expected)")
    }
  }

  func testProductionSuggestionsRunOnEveryContextCase() throws {
    let service = try Self.makeService()
    for context in SubstitutionEvidenceContexts.all {
      let suggestions = service.substitutions(for: Int64(context.originalId))
      let match = suggestions.first { $0.substituteId == Int64(context.substituteId) }
      guard let match else {
        XCTFail("no production suggestion for case \(context.caseId)")
        continue
      }
      XCTAssertEqual(match.ratio, context.productionRatio, accuracy: 1e-12, "ratio drifted in \(context.caseId)")

      // Dietary context must not remove the suggestion — restrictions only
      // reorder results, they never filter.
      let pair = SubstitutionEvidenceSnapshot.pairs.first {
        $0.originalId == context.originalId && $0.substituteId == context.substituteId
      }
      let restrictions = Self.restrictions(forReasons: pair?.reasons ?? [])
      let restricted = service.substitutions(
        for: Int64(context.originalId), dietaryRestrictions: restrictions)
      XCTAssertTrue(
        restricted.contains { $0.substituteId == Int64(context.substituteId) },
        "dietary context \(restrictions) removed the suggestion for \(context.caseId)")
    }
  }

  func testSourceRegionHashMatchesTheFixture() throws {
    XCTAssertEqual(try Self.sourceRegionSHA256(), SubstitutionEvidenceSnapshot.sourceRegionSHA256)
  }

  func testEveryPairHasPositiveFiniteRatioAndDistinctIngredients() {
    for pair in SubstitutionEvidenceSnapshot.pairs {
      XCTAssert(pair.ratio > 0 && pair.ratio.isFinite, "bad ratio in \(pair)")
      XCTAssertNotEqual(pair.originalId, pair.substituteId, "self-swap in \(pair)")
      XCTAssertFalse(pair.reasons.isEmpty, "no reasons in \(pair)")
      XCTAssertTrue(pair.reasons.allSatisfy { Self.reasonByKey[$0] != nil }, "unknown reason in \(pair)")
    }
  }

  func testContextCaseSetMatchesTheEvidenceCounts() {
    // 227 (pair, recipe) contexts as frozen in the evidence set.
    XCTAssertEqual(SubstitutionEvidenceContexts.all.count, 227)
  }
}
