// Generated by apps/ios/Tools/substitution-eval/tools/render_swift_fixture.py
// from evidence/pairs.snapshot.json. DO NOT EDIT by hand — rerun the script.

import Foundation

/// One production substitution pair, frozen from SubstitutionService.swift.
struct SubstitutionEvidencePair: Equatable {
  let originalId: Int
  let substituteId: Int
  let ratio: Double
  let reasons: [String]
}

enum SubstitutionEvidenceSnapshot {
  static let sourceRegionSHA256 = "1868a2650e94897892c489f9c07b0ca2c9f86db2f8a38448ba9cd65bb11250d4"
  static let pairs: [SubstitutionEvidencePair] = [
    SubstitutionEvidencePair(originalId: 14, substituteId: 16, ratio: 0.75, reasons: ["vegan", "dairyFree", "lighter"]),
    SubstitutionEvidencePair(originalId: 14, substituteId: 26, ratio: 1.0, reasons: ["vegan", "dairyFree"]),
    SubstitutionEvidencePair(originalId: 13, substituteId: 49, ratio: 1.0, reasons: ["vegan", "dairyFree"]),
    SubstitutionEvidencePair(originalId: 12, substituteId: 23, ratio: 1.2, reasons: ["vegan", "dairyFree", "lighter"]),
    SubstitutionEvidencePair(originalId: 32, substituteId: 49, ratio: 0.9, reasons: ["vegan", "dairyFree"]),
    SubstitutionEvidencePair(originalId: 50, substituteId: 32, ratio: 1.0, reasons: ["lighter"]),
    SubstitutionEvidencePair(originalId: 50, substituteId: 26, ratio: 0.8, reasons: ["vegan", "dairyFree"]),
    SubstitutionEvidencePair(originalId: 4, substituteId: 23, ratio: 1.0, reasons: ["vegan", "vegetarian"]),
    SubstitutionEvidencePair(originalId: 4, substituteId: 35, ratio: 1.3, reasons: ["vegan", "vegetarian"]),
    SubstitutionEvidencePair(originalId: 38, substituteId: 27, ratio: 1.2, reasons: ["vegan", "vegetarian"]),
    SubstitutionEvidencePair(originalId: 38, substituteId: 23, ratio: 1.0, reasons: ["vegan", "vegetarian"]),
    SubstitutionEvidencePair(originalId: 36, substituteId: 23, ratio: 1.0, reasons: ["vegan", "vegetarian"]),
    SubstitutionEvidencePair(originalId: 43, substituteId: 35, ratio: 1.2, reasons: ["vegan", "vegetarian"]),
    SubstitutionEvidencePair(originalId: 9, substituteId: 45, ratio: 1.5, reasons: ["glutenFree", "lowCarb"]),
    SubstitutionEvidencePair(originalId: 9, substituteId: 37, ratio: 1.0, reasons: ["glutenFree"]),
    SubstitutionEvidencePair(originalId: 15, substituteId: 37, ratio: 1.0, reasons: ["glutenFree"]),
    SubstitutionEvidencePair(originalId: 15, substituteId: 39, ratio: 0.5, reasons: ["glutenFree", "lowCarb"]),
    SubstitutionEvidencePair(originalId: 28, substituteId: 39, ratio: 0.5, reasons: ["glutenFree", "lowCarb"]),
    SubstitutionEvidencePair(originalId: 31, substituteId: 2, ratio: 1.0, reasons: ["glutenFree"]),
    SubstitutionEvidencePair(originalId: 1, substituteId: 20, ratio: 0.6, reasons: ["vegan"]),
    SubstitutionEvidencePair(originalId: 33, substituteId: 20, ratio: 1.5, reasons: ["vegan"]),
    SubstitutionEvidencePair(originalId: 17, substituteId: 29, ratio: 1.0, reasons: ["similar"]),
    SubstitutionEvidencePair(originalId: 29, substituteId: 17, ratio: 1.0, reasons: ["similar"]),
    SubstitutionEvidencePair(originalId: 5, substituteId: 21, ratio: 0.7, reasons: ["similar"]),
    SubstitutionEvidencePair(originalId: 21, substituteId: 5, ratio: 1.4, reasons: ["similar"]),
    SubstitutionEvidencePair(originalId: 10, substituteId: 37, ratio: 1.0, reasons: ["lighter"]),
    SubstitutionEvidencePair(originalId: 2, substituteId: 24, ratio: 1.0, reasons: ["lowCarb", "lighter"]),
  ]
}
